### PR TITLE
Search indexing

### PR DESCRIPTION
**Pull request by mielliott**
Added a CmdSimilar to discover similar contents. The *maximum number of similar matches for each content* and the *minimum similarity score threshold for a similar match to be recorded* are configurable.

e.g. `preston ls | preston similar --hits=10, --threshold=100`

A recorded similarity match currently looks like this (and I fully expect this to be changed):
```
<0b1be6f7-cb1b-4ec1-bf92-50da0518a4c9> <http://www.w3.org/ns/prov#value> "41.0"^^<http://www.w3.org/2001/XMLSchema#float> .
<0b1be6f7-cb1b-4ec1-bf92-50da0518a4c9> <http://www.w3.org/ns/prov#qualifiedGeneration> <19df8c55-d33d-4a03-9135-7895f0212b24> .
<19df8c55-d33d-4a03-9135-7895f0212b24> <http://www.w3.org/ns/prov#used> <hash://sha256/6d86c332b045e74fe4410f79655a1f47596808c057f30779b9584dba38fa25d5> .
<19df8c55-d33d-4a03-9135-7895f0212b24> <http://www.w3.org/ns/prov#used> <hash://sha256/1aa34112ade084ccc8707388fbc329dcb8fae5f895cb266e3ad943f7495740b3> .
```

Note that currently, for two TLSH hashes A and B, "similarity" is currently calculated as the number of bins that have the same value in both A and B. Since there are 134 bins in a TLSH hash, the maximum similarity score is 134. It might be more intuitive if we normalize it to [0, 1]. The TLSH paper describes a more complicated distance algorithm that considers the difference between bin values, not just exact matches. It might be helpful for us to do the same.

On the preston-amazon observatory, two random contents had a similarity of 41:
```
$ preston ls | grep wasDerivedFrom | head -n2 | preston similar --thresh=0
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#SoftwareAgent> <44702fd6-4531-4fe9-9e61-5715266de952> .
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Agent> <44702fd6-4531-4fe9-9e61-5715266de952> .
<https://preston.guoda.bio> <http://purl.org/dc/terms/description> "Preston is a software program that finds, archives and provides access to biodiversity datasets."@en <44702fd6-4531-4fe9-9e61-5715266de952> .
<44702fd6-4531-4fe9-9e61-5715266de952> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> <44702fd6-4531-4fe9-9e61-5715266de952> .
<44702fd6-4531-4fe9-9e61-5715266de952> <http://purl.org/dc/terms/description> "An event that generates similarity values between encountered contents (e.g., hash://sha256/... identifiers) that have been associated with a similarity hash (e.g., hash://tika-tlsh/...). The process currently uses similarity hashes (e.g., Trend Micro Locality Sensitive Hash, https://github.com/trendmicro/tlsh/blob/master/TLSH_CTC_final.pdf) calculated on content text extracted using https://tika.apache.org."@en <44702fd6-4531-4fe9-9e61-5715266de952> .
<44702fd6-4531-4fe9-9e61-5715266de952> <http://www.w3.org/ns/prov#startedAtTime> "2020-07-14T17:48:45.145Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> <44702fd6-4531-4fe9-9e61-5715266de952> .
<44702fd6-4531-4fe9-9e61-5715266de952> <http://www.w3.org/ns/prov#wasStartedBy> <https://preston.guoda.bio> <44702fd6-4531-4fe9-9e61-5715266de952> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/ns/prov#usedBy> <44702fd6-4531-4fe9-9e61-5715266de952> <44702fd6-4531-4fe9-9e61-5715266de952> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/dcmitype/Software> <44702fd6-4531-4fe9-9e61-5715266de952> .
<https://doi.org/10.5281/zenodo.1410543> <http://purl.org/dc/terms/bibliographicCitation> "Jorrit Poelen, Icaro Alzuru, & Michael Elliott. 2019. Preston: a biodiversity dataset tracker (Version 0.0.1-SNAPSHOT) [Software]. Zenodo. http://doi.org/10.5281/zenodo.1410543"@en <44702fd6-4531-4fe9-9e61-5715266de952> .
<0659a54f-b713-4f86-a917-5be166a14110> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Entity> <44702fd6-4531-4fe9-9e61-5715266de952> .
<0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/dc/terms/description> "A biodiversity dataset graph archive."@en <44702fd6-4531-4fe9-9e61-5715266de952> .
<hash://sha256/c2faaeac7467d99f6567f4f72a5370ea77c7829524f39e2603df7ae6f657d7ba> <http://www.w3.org/ns/prov#usedBy> <44702fd6-4531-4fe9-9e61-5715266de952> <44702fd6-4531-4fe9-9e61-5715266de952> .
<hash://tika-tlsh/253af515a4ff1c20add297ab08925df37d2ff42e9d048d8e20c72f1609477a96385> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/1aa34112ade084ccc8707388fbc329dcb8fae5f895cb266e3ad943f7495740b3> <aa08b5cb-78c3-46f5-81b3-e8726cc1e2f5> .
<hash://tika-tlsh/282ee27a09f35136a5b950bfe468747e3f258f6e5ca14094940f9914ce30b7371ca> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/6d86c332b045e74fe4410f79655a1f47596808c057f30779b9584dba38fa25d5> <51ccff27-dc62-4123-8a26-7491b9a644fe> .
<7256130b-23ef-4b20-9f5c-fb837e18cc89> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> <7256130b-23ef-4b20-9f5c-fb837e18cc89> .
<7256130b-23ef-4b20-9f5c-fb837e18cc89> <http://www.w3.org/ns/prov#wasInformedBy> <51ccff27-dc62-4123-8a26-7491b9a644fe> <7256130b-23ef-4b20-9f5c-fb837e18cc89> .
<0b1be6f7-cb1b-4ec1-bf92-50da0518a4c9> <http://www.w3.org/ns/prov#value> "41.0"^^<http://www.w3.org/2001/XMLSchema#float> <7256130b-23ef-4b20-9f5c-fb837e18cc89> .
<0b1be6f7-cb1b-4ec1-bf92-50da0518a4c9> <http://www.w3.org/ns/prov#qualifiedGeneration> <19df8c55-d33d-4a03-9135-7895f0212b24> <7256130b-23ef-4b20-9f5c-fb837e18cc89> .
<19df8c55-d33d-4a03-9135-7895f0212b24> <http://www.w3.org/ns/prov#used> <hash://sha256/6d86c332b045e74fe4410f79655a1f47596808c057f30779b9584dba38fa25d5> <7256130b-23ef-4b20-9f5c-fb837e18cc89> .
<19df8c55-d33d-4a03-9135-7895f0212b24> <http://www.w3.org/ns/prov#used> <hash://sha256/1aa34112ade084ccc8707388fbc329dcb8fae5f895cb266e3ad943f7495740b3> <7256130b-23ef-4b20-9f5c-fb837e18cc89> .
```

Running on the full preston-amazon observatory (default 100 max hits, 100 similarity score threshold) found 17,517 similar content pairs across 1,438 unique contents, and took 3m42s to run:
```
$ time preston ls | preston similar > out
real    3m42.092s
user    0m56.188s
sys     1m6.141s
$ cat out | grep "#wasDerivedFrom" | wc -l
1438
$ cat out | grep "#value" | wc -l
17517
```

The distribution of similarity scores:
```
$ cat out-similar | grep "#value" | cut -c75- | cut -c-3 | sort | uniq -c | sort -nr -k2
     45 134
     45 132
     80 131
     80 130
    160 129
    194 128
    160 127
    338 126
     80 125
    374 124
    214 123
     80 122
     90 121
   2251 120
    408 119
   5363 118
    178 117
    134 113
    269 108
    159 106
    447 103
    284 102
    159 101
    667 100
    125 99.
     96 98.
    282 97.
    150 96.
    128 95.
    395 94.
    162 93.
    141 92.
    168 91.
    158 90.
    223 89.
    178 88.
     62 87.
     82 86.
     25 85.
     70 84.
    102 83.
    141 82.
     24 81.
      3 80.
     61 79.
     27 78.
     27 77.
     55 76.
     49 75.
    117 73.
      3 72.
     24 71.
     36 70.
     21 69.
     38 67.
     62 66.
     17 65.
    105 64.
    102 63.
     89 62.
    126 61.
    129 60.
    105 59.
     50 58.
     37 57.
    133 56.
     97 55.
     47 54.
    114 53.
     66 52.
     96 51.
     43 50.
    114 49.
    111 48.
    105 47.
      1 46.
    120 45.
      6 44.
     27 43.
     48 42.
     42 41.
      9 40.
      9 39.
     36 38.
     21 37.
     18 33.
```

### CODE REVIEW

**Comment by jhpoelen** [comment]
Thanks for sharing. Before I try and reproduce your findings, I wanted to check which observatory you used. The currently preston-amazon has 119 data objects.

```
$ find -type f  | wc -l
119
```

 However, you mentioned that you saw ```1,438 unique contents```. Can you share the provenance hash associated with the observatory you used?

**Comment by mielliott** [comment]
Thanks for bringing that up. Looking back, that number wasn't for "unique" contents. Also, my local preston-amazon copy had a long history of whatever tests I had been running, so instead of giving you one of those prov hashes, I just recloned the preston-amazon repo and ran the tests again (latest prov: `hash://sha256/1aa34112ade084ccc8707388fbc329dcb8fae5f895cb266e3ad943f7495740b3`)

```
$ time preston ls | preston tika | preston similar > out
real    0m38.741s
user    0m27.438s
sys     0m14.313s
$ cat out | grep "#wasDerivedFrom" | wc -l
532
$ cat out | grep "#value" | wc -l
3280
```
And if I try again after eliminating duplicate `<tika-tlsh> <derivedFrom> <sha256> .` quads:
```
$ time preston-dev ls | preston-dev tika | grep "#wasDerivedFrom" | grep "hash://tika-tlsh/" | cut -c-210 |  sed 's/$/ ./' | sort | uniq | preston-dev similar > out
real    0m17.428s
user    0m19.641s
sys     0m5.422s
$ cat out | grep "#wasDerivedFrom" | wc -l
108
$ cat out | grep "#value" | wc -l
50
```
Note that, for both of these tests, the default threshold=100 was used. That's all I've got time for right now, I'll probably explore more later.

**Comment by jhpoelen** [comment]
@mielliott thanks for the update.

I was able to reproduce:

```
$ time preston ls | preston tika | preston similar > out

real	0m25.025s
user	1m12.067s
sys	0m4.516s
$ cat out | grep "#wasDerivedFrom" | wc -l
532
```

however, for some reason,
```
$ cat out | grep "#value" | wc -l
3310
```
instead of your 

```
$ cat out | grep "#value" | wc -l
3280
```

Any idea why? I've attached my out here: 
[out.txt.gz](https://github.com/bio-guoda/preston/files/4927104/out.txt.gz)



Some addition comments / questions: 

1. for some reason, the folder ```tmp:index``` was created, I expected the existing temp folder ```tmp``` to be re-used. 
2. do you keep the calculated search index around? If so, how do you link it to a specific set of processed statements?

**Comment by mielliott** [comment]
This branch has already been merged (5ed504b684c307b14a56b8432416ddca591c2c22). Closing pull request.

**Pull request closed without merging**
